### ISSUE TITLE
should not convert quotes already in template literal

### ISSUE THREAD

**Issue by tao-cumplido** [meganrogge/template-string-converter#11]
I just noticed when you have something like

```js
html`<span class="">`
```

the plugin wrongly detects the inner `"` quotes and converts them to `` ` `` when typing `${` inside, so the above turns into

```js
html`<span class=`${}`>`
```

which is invalid code

**Comment by meganrogge** [comment]
This extension shouldn’t work for html files. I will look into this.

**Comment by tao-cumplido** [comment]
I don't think the tagged template is detected as html file just because the function is named `html`. I am using [lit-html](https://lit-html.polymer-project.org/) by the way.

**Comment by meganrogge** [comment]
Oh okay that’s helpful to know. I think I know how to solve this and will implement the fix soon.

**Comment by meganrogge** [comment]
resolved in 0.1.3 which should be available in a few minutes.

**Comment by tao-cumplido** [comment]
Hey, thanks for the quick fix. I just noticed that it is still a problem in multiline template literals.

```js
const foo = `
  ""
`;
```
will result in
```js
const foo = `
  `${}`
`;
```

**Comment by meganrogge** [comment]
At this time multiline isn’t supported. I might work on that soon though.
